pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
      
    
    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube'){
                   sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=soundiata12_geo.project'    
                }
    
        }
        }
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP5Nti3MTn5mzHPk7Qx7Y6yNhQt -T \
                 target/bio*.jar \
                  "http://44.203.117.160:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar" '
            }

        }
    }

}