pipeline {
    agent any 

    stages{
        stage("maven"){
            steps {
                sh 'mvn clean package'
            }
        }

        stage("compile"){
            steps{
                sh 'mvn compile'
            }
           
        }
        stage('test'){
            steps{
                sh 'mvn install'
            }
        }
    }
}
    
    
        
